---
galaxy_info:
  author: Raphael Morsch
  description: Prepare hosts for Podman based container workloads.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
dependencies: []
